AWSTemplateFormatVersion: 2010-09-09
Transform: TempLoop
Description: >
  Sample template for TempLoop.

Parameters:
  NameSuffixList:
    Type: CommaDelimitedList
    Default: 1, 2, 3

Resources:
  Function:
    Type: List<AWS::Lambda::Function>
    Metadata:
      TempLoop::Iteration: !Ref NameSuffixList
    Properties:
      Code:
        ZipFile: |
          def handler(event, context):
            pass
      FunctionName: !Sub temploop-sample-function-${TempLoop::Item}
      Description: The function for testing TempLoop.
      Handler: index.handler
      MemorySize: 128
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/temploop-lambda-role
      Runtime: python3.6

Outputs:
  FunctionArnList:
    Value: !Join
      - ','
      - !GetAtt Function.Arn
